### PR TITLE
Pin HDF5 version and fix Mac builds

### PR DESCRIPTION
**Pull request by 183amir**
This pull merges both https://github.com/conda-forge/bob.io.base-feedstock/pull/1 and https://github.com/conda-forge/bob.io.base-feedstock/pull/2.

### CODE REVIEW

**Comment by 183amir** [comment]
@jakirkham or @pelson I merged both pull requests into one and everything seems to be working.
If you have no objection, I will merge this.

**Comment by jakirkham** [comment]
If it seems to be working, go for it. Though @ocefpaf is currently the most knowledgeable on the pinning front at this point.

**Comment by ocefpaf** [comment]
The `hdf5` case:
- `1.8.15*` is preferred because that will be compatible with the default channel (`libnetcdf`) and most of conda-forge.
- `1.8.16*`is the latest version added in conda-forge, but currently used in just a few packages (`bob.io.base`, `caffe`, `libmatio`, and `flann`).

**Comment by 183amir** [comment]
@ocefpaf In a `bob` environment we use `libmatio` but not `libnetcdf`.
However, both `bob.io.base` and `libmatio` are not pinned on any version of `hdf5`.
Here I am pinning `bob.io.base` against `hdf-1.8.15*` but seems like pinning it against `hf5-1.8.16*` would be more useful. Do you agree?

**Comment by jakirkham** [comment]
On `hdf5`, it looks like `1.8.15*` is used here so should be good. We fixed `caffe` last week.

**Comment by jakirkham** [comment]
Nah, I think we should have HDF5 pinned the same way across the board. Not doing this has caused all sorts of problems. For instance, someone might want your packages and `h5py` too. Then they will have issues due to these dependency issues.

**Comment by 183amir** [comment]
Ok. So let's wait for https://github.com/conda-forge/libmatio-feedstock/issues/3 to get resolved and I will rebuild this pull again to make sure it works.

**Comment by ocefpaf** [comment]
> @ocefpaf In a `bob` environment we use `libmatio` but not `libnetcdf`.
> However, both `bob.io.base` and `libmatio` are not pinned on any version of `hdf5`.
> Here I am pinning `bob.io.base` against `hdf-1.8.15*` but seems like pinning it against `hf5-1.8.16*` would be more useful. Do you agree?

The pinning must be consistent among your ecosystem. So you have to choose either between `hfd5-1.8.16*` or `hfd5-1.8.15*` for all `bob-<packages>`, dependencies, and software you wish to install along side them. Bare in mind that, even though we have `hfd5-1.8.16` packaged we are moving away from it until we have a `libetcdf` compiled against it.

I would say the safe choice is `hfd5-1.8.15*`.

**Comment by 183amir** [comment]
Ok I will use `hfd5-1.8.15*` then.

**Pull request merged**
